News integration
alkemyTech/OT115-Android pull request #10
Opened 2021-12-01 01:40 UTC by PBeltran95

Api news response integration, api error handling, news screen finished.
Tickets 36, 37, 38.

![image](https://user-images.githubusercontent.com/86982267/144156133-85471c2d-d88a-409b-8ab7-947582608457.png)

2021-12-01 22:46 UTC, MelvinKucuk requested changes

2021-12-01 22:46 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongandroid/view/LoginActivity.kt
> +import com.alkemy.ongandroid.viewmodel.ApiDataViewModel
Imports innecesarios

2021-12-01 22:46 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongandroid/view/fragments/news/NewsFragment.kt
> +    private lateinit var binding: FragmentNewsBinding
te falto darle valor al binding en el `onCreateView()`

2021-12-01 23:11 UTC, PBeltran95 commented on app/src/main/java/com/alkemy/ongandroid/view/fragments/news/NewsFragment.kt
> +    private lateinit var binding: FragmentNewsBinding
Tenes razón, se me paso 😑! Ahora lo agrego.

2021-12-01 23:14 UTC, PBeltran95 commented on app/src/main/java/com/alkemy/ongandroid/view/LoginActivity.kt
> +import com.alkemy.ongandroid.viewmodel.ApiDataViewModel
Arreglados.

2021-12-01 23:30 UTC, MelvinKucuk requested changes

2021-12-01 23:30 UTC, MelvinKucuk commented on app/src/main/res/layout/activity_login.xml
> +>>>>>>> 5a26929ab61062318deb31668d1436d3fb956549
te quedo esto raro de algun merge

2021-12-02 00:48 UTC, PBeltran95 commented on app/src/main/res/layout/activity_login.xml
> +>>>>>>> 5a26929ab61062318deb31668d1436d3fb956549
Sin querer mergie sin hacer commit ni add y me parece que fue eso, ahi lo corregí

2021-12-02 16:22 UTC, MelvinKucuk approved these changes

2021-12-02 16:22 UTC, merged