Login to main
alkemyTech/OT115-Android pull request #11
Opened 2021-12-01 02:33 UTC by pasaporteN25

2021-12-01 15:45 UTC, MelvinKucuk requested changes

2021-12-01 15:45 UTC, MelvinKucuk commented on app/build.gradle
> -
No tocaria este archivo

2021-12-01 15:45 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongandroid/view/LoginActivity.kt
> +            }
esta validacion la deberia hacer el viewModel

2021-12-01 15:45 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongandroid/view/LoginActivity.kt
> +            }
Hasta podrias comprobar si el llamado fuen un 200

2021-12-01 15:45 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongandroid/view/LoginActivity.kt
> +        //comprobar si no toma los campos vacios!!
que los comentarios no queden en el PR

2021-12-01 15:45 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongandroid/view/LoginActivity.kt
> +        //admin@admin - pass: admin
idem

2021-12-01 15:45 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongandroid/view/MainActivity.kt
> +        //startActivity(intent)
codigo comentado

2021-12-01 15:45 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongandroid/viewmodel/LoginViewModel.kt
> +                    //Rompe por ser nulo, algo que el if deberia evitar??
En que linea dice que rompe? Y que indica que es null?

2021-12-01 15:57 UTC, pasaporteN25 commented on app/src/main/java/com/alkemy/ongandroid/viewmodel/LoginViewModel.kt
> +                    //Rompe por ser nulo, algo que el if deberia evitar??
En la linea de arriba del comentario >if(resp!=null) 
Rompe si mando la consulta con los campos vacios, no se si esa responsabilidad esta en otra tarea o deberia haberla tenido en cuenta.

2021-12-01 16:11 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongandroid/viewmodel/LoginViewModel.kt
> +                    //Rompe por ser nulo, algo que el if deberia evitar??
tenes captura del error?

2021-12-01 18:45 UTC, pasaporteN25 commented on app/src/main/java/com/alkemy/ongandroid/viewmodel/LoginViewModel.kt
> +                    //Rompe por ser nulo, algo que el if deberia evitar??
![error al enviar datos vacios](https://user-images.githubusercontent.com/16930095/144294739-ab6e6ffd-89ca-4708-8475-e978780ec4a7.jpg)

2021-12-01 19:01 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongandroid/viewmodel/LoginViewModel.kt
> +                    //Rompe por ser nulo, algo que el if deberia evitar??
Lo que esta viniendo null es el Data el info no es null pero el Data de adentro parece que si

2021-12-01 22:55 UTC, MelvinKucuk requested changes

2021-12-01 22:55 UTC, MelvinKucuk commented on app/build.gradle
> -
Sigue estando el archivo con cambios

2021-12-01 22:55 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongandroid/viewmodel/LoginViewModel.kt
> +        class Failure(): State()
Como mejora pueden ser object y no class, el codigo quedaria

`
object Success: State()
object Failure: State()
`

2021-12-02 16:33 UTC, MelvinKucuk requested changes

2021-12-02 16:33 UTC, MelvinKucuk commented on app/build.gradle
> -
Este archivo no lo tocaria

2021-12-02 22:01 UTC, MelvinKucuk approved these changes

2021-12-02 22:01 UTC, merged