Feature/ot115 32 add bottom navigation bar
alkemyTech/OT115-Android pull request #12
Opened 2021-12-01 12:56 UTC by mardbel

https://alkemy-labs.atlassian.net/browse/OT115-32

2021-12-01 15:34 UTC, MelvinKucuk requested changes

2021-12-01 15:34 UTC, MelvinKucuk commented on app/build.gradle
> +    implementation 'androidx.core:core-ktx:1.3.2'
aca dejaria la ultima version de core-ktx

2021-12-01 15:34 UTC, MelvinKucuk commented on app/build.gradle
> +    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
estos estan repetidos

2021-12-01 15:34 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongandroid/businesslogic/api/di/RemoteModule.kt
> +    @ApplicationContext
hace falta esta annotation?

2021-12-01 15:34 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongandroid/businesslogic/api/di/RemoteModule.kt
> +    @ApplicationContext
hace falta esta annotation?

2021-12-01 15:34 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongandroid/view/SignUpActivity.kt
> +        }
aca no sacaria el metodo de `setUpObservers()` dejaria la declaracion del observer en su propio metodo

2021-12-01 15:34 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongandroid/view/SignUpActivity.kt
> +        onSaveUserBtnClick()
esta linea de `onSaveUserBtnClick()` deberia ir adentro del onClickListener del boton

2021-12-02 22:10 UTC, MelvinKucuk requested changes

2021-12-02 22:10 UTC, MelvinKucuk commented on app/src/main/AndroidManifest.xml
>  </manifest>
Este archivo no lo tocaria

2021-12-02 22:10 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongandroid/businesslogic/api/OngApiService.kt
>  package com.alkemy.ongandroid.businesslogic.api
este archivo no es parte del scope de la tarea ni del branch

2021-12-02 22:10 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongandroid/model/UserRepository.kt
este archivo no es parte del scope de la tarea ni del branch

2021-12-02 22:10 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongandroid/model/UserRequest.kt
>  package com.alkemy.ongandroid.model
este archivo no es parte del scope de la tarea ni del branch

2021-12-02 22:10 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongandroid/view/SignUpActivity.kt
>  import android.os.Bundle
este archivo no es parte del scope de la tarea ni del branch

2021-12-02 22:10 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongandroid/viewmodel/SignUpViewModel.kt
>  import androidx.lifecycle.viewModelScope
este archivo no es parte del scope de la tarea ni del branch

2021-12-02 22:10 UTC, MelvinKucuk commented on app/src/main/res/layout/activity_sign_up.xml
>          style="@style/TitleFormStyle"
este archivo no es parte del scope de la tarea ni del branch

2021-12-02 23:15 UTC, mardbel commented on app/src/main/AndroidManifest.xml
>  </manifest>
Agregué la activity nueva LoginSuccessActivity y movi el launcher para hacer pruebas, cuando se lo puse de nuevo a la Splash activity quedo diferencia de una linea vacia pero nada mas.

2021-12-02 23:20 UTC, mardbel commented on app/src/main/java/com/alkemy/ongandroid/model/UserRepository.kt
cuando actualicé de develop la clase User fue actualizada por UserRequest, asi que tuve que hacer todos los cambios donde se usaba.

2021-12-02 23:23 UTC, mardbel commented on app/src/main/java/com/alkemy/ongandroid/model/UserRequest.kt
>  package com.alkemy.ongandroid.model
Actualicé la clase User por UserRequest porque me pareció más descriptivo.

2021-12-02 23:24 UTC, mardbel commented on app/src/main/java/com/alkemy/ongandroid/viewmodel/SignUpViewModel.kt
>  import androidx.lifecycle.viewModelScope
Cambios para usar UserRequest en lugar de User.

2021-12-02 23:32 UTC, mardbel commented on app/src/main/res/layout/activity_sign_up.xml
>          style="@style/TitleFormStyle"
Tenes razon, no tendría que haber tocado aca, pero si te fijas, lo que borre lo volvi a agregar igual como estaba.

2021-12-02 23:34 UTC, mardbel commented on app/src/main/java/com/alkemy/ongandroid/businesslogic/api/OngApiService.kt
>  package com.alkemy.ongandroid.businesslogic.api
Actualicé la clase User por UserRequest, ya me parecía más claro. Asi que tuve que hacer todos los cambios donde se usaba.

2021-12-02 23:43 UTC, mardbel commented on app/src/main/java/com/alkemy/ongandroid/view/SignUpActivity.kt
>  import android.os.Bundle
Aca estaba repasando la parte mia y hice ctrl +alt + L para formatear y cambio de lugar muchas de las lineas de Mauri, pero si te fijas, quedo todo igual, solo que acomodado diferente.

2021-12-03 21:17 UTC, MelvinKucuk approved these changes

2021-12-03 21:17 UTC, merged