Error screen OT-115-42
alkemyTech/OT115-Android pull request #13
Opened 2021-12-01 22:27 UTC by pasaporteN25

2021-12-01 22:52 UTC, MelvinKucuk requested changes

2021-12-01 22:52 UTC, MelvinKucuk commented on app/build.gradle
> -
esto de aca no lo tocaria

2021-12-01 22:52 UTC, MelvinKucuk commented on app/build.gradle
> +    //
no se si querias aclarar la libreria que traias o se te olvido de borrar

2021-12-01 22:52 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongandroid/view/LoginActivity.kt
Este archivo no es parte del scope del branch ni del ticket

2021-12-01 22:52 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongandroid/view/MainActivity.kt
>      override fun onCreate(savedInstanceState: Bundle?) {
Este archivo no es parte del scope del branch ni del ticket

2021-12-01 22:52 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongandroid/view/SplashActivity.kt
Este archivo no es parte del scope del branch ni del ticket

2021-12-01 22:52 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongandroid/viewmodel/LoginViewModel.kt
>      private val localDataManager: LocalDataManager
Este archivo no es parte del scope del branch ni del ticket

2021-12-01 22:52 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongandroid/viewmodel/SignUpViewModel.kt
>              val response = repository.addUserToRemoteDB(user)
Este archivo no es parte del scope del branch ni del ticket

2021-12-01 22:52 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongandroid/view/MyApplication.kt
> +        CaocConfig.Builder.create()
Faltaria definir que vaya al Login Activity porque esta yendo al Splash

2021-12-02 01:49 UTC, pasaporteN25 commented on app/src/main/java/com/alkemy/ongandroid/view/LoginActivity.kt
Yo no teoque esta activity ni las otras que estan fuera de scope no entiendo, pero bueno me pasa por usar el "git add ." JAJA perdon, empezare a discriminar por archivo

2021-12-02 22:01 UTC, MelvinKucuk approved these changes, later dismissed

2021-12-02 22:15 UTC, MelvinKucuk approved these changes

2021-12-02 22:15 UTC, merged