Sign in gfb OT115-68
alkemyTech/OT115-Android pull request #21
Opened 2021-12-08 20:23 UTC by pasaporteN25

2021-12-08 20:24 UTC, pasaporteN25 commented
Me agarro algunos commits viejos, creo que porque me olvide de crear la rama nueva de entrada. El primer commit de esta branch seria "Job almost done" -> 24267a8...

2021-12-09 16:06 UTC, MelvinKucuk requested changes

2021-12-09 16:06 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongandroid/viewmodel/LoginViewModel.kt
>  import androidx.lifecycle.viewModelScope
No tocaria esta clase

2021-12-09 20:41 UTC, pasaporteN25 commented on app/src/main/java/com/alkemy/ongandroid/viewmodel/LoginViewModel.kt
>  import androidx.lifecycle.viewModelScope
Listo, revertido.

2021-12-09 21:17 UTC, MelvinKucuk approved these changes

2021-12-09 21:17 UTC, merged