Members api
alkemyTech/OT115-Android pull request #32
Opened 2021-12-14 21:33 UTC by maxiantonelli97

2021-12-14 22:07 UTC, MelvinKucuk requested changes

2021-12-14 22:07 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongandroid/view/adapters/UsAdapter.kt
> +                tvUsPosition.text = this.description  ?: "NO DATA"
aca para poder usar el string podes hacer `root.context.getString(R.string.woinfo)`

2021-12-14 22:07 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongandroid/view/fragments/UsFragment.kt
> +            (activity as? BaseActivity)?.setCustomProgressBarVisibility(false)
Esta linea esta demas ya que la deberias manejar con el Loading y un booleano

2021-12-15 17:53 UTC, maxiantonelli97 commented on app/src/main/java/com/alkemy/ongandroid/view/fragments/UsFragment.kt
> +            (activity as? BaseActivity)?.setCustomProgressBarVisibility(false)
Podrías aclararme un poco más esto? Por favor

2021-12-15 18:30 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongandroid/view/fragments/UsFragment.kt
> +            (activity as? BaseActivity)?.setCustomProgressBarVisibility(false)
Si fijate en ejemplos de otros viewmodel con el Loading, el Loading deberia ser una clase con un val booleano que indique si esta cargando o no. Ese en un approach como el WelcomeViewModel o podes tener otro como el del LoginViewModel

2021-12-18 00:15 UTC, MelvinKucuk requested changes

2021-12-18 00:15 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongandroid/view/fragments/UsFragment.kt
> +        viewModel.Status.value = false
esta linea no creo que haga nada porque la idea es desde el fragment, observar el valor del liveData y dependiendo de ese valor mostrar o no el progressBar

2021-12-21 21:43 UTC, MelvinKucuk approved these changes

2021-12-21 21:43 UTC, merged