Login req
alkemyTech/OT115-Android pull request #6
Opened 2021-11-26 20:35 UTC by pasaporteN25

https://alkemy-labs.atlassian.net/browse/OT115-25

2021-11-29 12:23 UTC, MelvinKucuk requested changes

2021-11-29 12:23 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongandroid/api/ApiONG.kt
> +        @Field("password") password: String
en vez de usar parametros estaria mejor usar una data class que contenga las variables y agregarla con `@Body`

2021-11-29 12:23 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongandroid/api/ApiONGImp.kt
> +        return resp
Despues de que se integre Hilt en el proyecto migrar esto a Hilt, los nombres de metodos no deberian empezar con mayuscula

2021-11-29 12:23 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongandroid/model/User.kt
> +    @SerializedName("id") var id: Int?    = null,
aca hay espacios innecesarios despues de Int?

2021-11-29 12:23 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongandroid/model/User.kt
> +    @SerializedName("profile_image") var profileImage: String? = null
queda mas prolijo tener el SerializedName en una linea y la variable en otra

2021-11-29 12:23 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongandroid/view/LoginActivity.kt
> +        LoginVM = ViewModelProvider(this).get(LoginViewModel::class.java)
Esta bien la inicializacion, te dejo de tarea despues migrarlo a Hilt

2021-11-29 12:23 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongandroid/view/LoginActivity.kt
> +    private lateinit var LoginVM: LoginViewModel
nombres de variables tampoco deberian empezar con mayuscula

2021-11-29 12:23 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongandroid/view/LoginActivity.kt
> +        }
La corrutina deberia ser lanzada desde el viewModel y no desde la activity

2021-11-29 12:23 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongandroid/view/LoginActivity.kt
> +    }
Deberia ir al viewmodel, el Toast creo que es innecesario, si te sirve para desarrollo despues al momento del PR lo sacas y todos los Strings que usas deberian ser constantes

2021-11-29 12:23 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongandroid/view/MainActivity.kt
> +import com.alkemy.ongandroid.viewmodel.LoginViewModel
import innecesario

2021-11-29 12:23 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongandroid/viewmodel/LoginViewModel.kt
> +            Log.e("Hasta k: ", "master Master master")
Estos logs si son de desarrollo no deberian quedar en el PR al proyecto

2021-11-29 12:23 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongandroid/viewmodel/LoginViewModel.kt
> +    private var loginfo = ArrayList<ResponseLogin>()
es mejor usar las `List` de kotlin que los ArrayList

2021-11-29 12:23 UTC, MelvinKucuk commented on app/src/main/java/com/alkemy/ongandroid/viewmodel/LoginViewModel.kt
> +                Log.e("Data: ", info.success)
Estos logs si son de desarrollo no deberian quedar en el PR al proyecto, en este caso ya la instancia de retrofit del proyecto esta pensada para que logee el flujo de request y response

2021-11-29 12:23 UTC, MelvinKucuk commented on app/build.gradle
> +    implementation 'androidx.navigation:navigation-ui-ktx:2.3.5'
Estos los usaste?

2021-11-29 12:23 UTC, MelvinKucuk commented on build.gradle
> +        classpath"androidx.navigation:navigation-safe-args-gradle-plugin:2.3.5"
Esto lo usaste?

2021-11-29 12:24 UTC, MelvinKucuk commented
Si actualizas el branch con develop podrias resolver los conflictos

2021-11-29 15:30 UTC, pasaporteN25 commented
Con eso de que actualice el branch a develop me estas diciendo que haga un pull de develop antes de volver a hacer el pr? No afectaria al trabajo que tengo en mi rama?

2021-11-29 15:43 UTC, MelvinKucuk commented
> Con eso de que actualice el branch a develop me estas diciendo que haga un pull de develop antes de volver a hacer el pr? No afectaria al trabajo que tengo en mi rama?

Tendrias que resolver los conflictos del merge tratando de que quede tu desarrollo y el de los demas, cualquier cosa para resolver los conflictos lo hacemos juntos y se puede hacer despues de que corrigas lo comentado

2021-11-29 16:39 UTC, pasaporteN25 commented
Listo, ya resolvi lo de mas arriba. Seguro algo mas se puede mejorar, asi que quedo pendiente de si tenes algun cambio mas para sugerirme. En cuanto a los conflictos ¿Los puedo resolver desde aca mismo borrando las lineas que considere que no van verdad? Sino espero y lo vemos, no te quiero joder.

2021-11-29 18:57 UTC, MelvinKucuk commented on app/build.gradle
> +    implementation 'androidx.navigation:navigation-ui-ktx:2.3.5'
Esta libreria la usas?

2021-11-29 18:59 UTC, pasaporteN25 commented on app/build.gradle
> +    implementation 'androidx.navigation:navigation-ui-ktx:2.3.5'
Cuando la saque me rompia el "ViewModelProvider" no entendi el porque pero decidi conservarla por ese motivo.

2021-11-29 21:56 UTC, MelvinKucuk commented on app/build.gradle
> +    implementation 'androidx.navigation:navigation-ui-ktx:2.3.5'
cambiala por esta `implementation 'androidx.activity:activity-ktx:1.4.0'` internamente es trae esta pero nosotros solo nececitamos la de activity

2021-11-30 00:40 UTC, MelvinKucuk approved these changes

2021-11-30 00:40 UTC, merged